repos:
- repo: https://github.com/ambv/black
  rev: 22.6.0
  hooks:
    - id: black

- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
  
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
    - id: isort
  
- repo: https://github.com/econchick/interrogate
  rev: 1.5.0
  hooks:
    - id: interrogate
      args: [-vv, -i, --fail-under=80 ]
      